name: Converti Glossario PDF a HTML

on:
  push:
    branches:
      - main
      - feature/SCRUM-88-Automazione-lettura-file-da-Pages #TODO: Rimuovere alla fine della feature
    paths-ignore:
      - 'glossario.html'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  convert_pdf_to_html:
    runs-on: ubuntu-latest

    steps:
      # Passaggio 1: Effettua il checkout del codice
      - name: Checkout del codice
        uses: actions/checkout@v2

      # Passaggio 2: Installa uv
      - name: Installa uv
        uses: astral-sh/setup-uv@v5

      # Passaggio 3: Installa i pacchetti necessari (poppler-utils per pdftotext)
      - name: Installa pdftotext
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      # Passaggio 4: Scarica il PDF da un link dinamico
      - name: Scarica il PDF da un link dinamico
        run: |
          curl -o index.json https://teamcodealchemists.github.io/docs/index.json
          PDF_URL=$(jq -r '.glossario[0].link' index.json)
          curl -o glossario.pdf "$PDF_URL"

      # Passaggio 5: Estrai il testo dal PDF
      - name: Estrai il testo dal PDF
        run: pdftotext glossario.pdf glossario.txt

      # Passaggio 6: Converte il testo in HTML
      - name: Converte il testo in HTML
        run: uv run .github/workflows/glossario_convert.py

      # Passaggio 7: Effettua il commit e il push del file HTML nel repository
      - name: Commit e push del file HTML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add glossario.html
          git commit -m "Aggiorna glossario.html" || echo "Nessuna modifica da commettere"
          git pull --rebase --strategy-option=ours
          git push