name: Controllo Ortografico Documentazione

on: [push]
  
  #:
  #  paths:
  #    - 'documents/**/*.pdf'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v2

      - name: Installa pdftotext
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Estrai testo dai PDF
        run: |
            find ./documents -name "*.pdf" | while IFS= read -r file; do
              pdftotext "$file" "${file%.pdf}.txt"
            done

      - name: Esegui LanguageTool con reviewdog
        uses: reviewdog/action-languagetool@v1.22.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          language: 'it-IT'
          patterns: '**/*.txt'
          level: 'warning'
          reporter: 'github-pr-review'

